.

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -71,12 +71,14 @@ services:
         max-size: 100m
 
   gui:
-    image: dojot/gui:v0.4.2
+    image: mprevide/gui:test_fix  #dojot/gui:report_axis_y
     restart: always
     logging:
       driver: json-file
       options:
         max-size: 100m
+    environment:
+      GUI_VERSION: 'compose123'
 
   data-broker:
     image: dojot/data-broker:v0.4.2
@@ -225,58 +227,164 @@ services:
       options:
         max-size: 100m
 
-  postgres-users:
-    image: dojot/postgres:9.4.24-alpine
-    restart: on-failure
-    command: >
-      bash -c "if ! psql -h postgres -U postgres -t -c '\du' | cut -d \| -f 1 | grep -qw kong; then
-                   echo 'creating user kong'
-                   createuser kong -d -h postgres -U postgres
-               else
-                   echo 'user kong exists'
-               fi
-               if ! psql -h postgres -U postgres -lqt | cut -d \| -f 1 | grep -qw kong; then
-                   echo 'creating database kong'
-                   createdb kong -U kong -h postgres
-               else
-                   echo 'database kong exists'
-               fi"
-    depends_on:
-      postgres:
-        condition: service_healthy
-    logging:
-      driver: json-file
-      options:
-        max-size: 100m
-
-  kong-migration:
-    image: dojot/kong:v0.4.2
-    depends_on:
-      postgres:
-        condition: service_healthy
+  db:
+    image: postgres:9.5
     environment:
-      - KONG_DATABASE=postgres
-      - KONG_PG_HOST=postgres
-    command: kong migrations up
+      POSTGRES_DB: ${KONG_PG_DATABASE:-kong}
+      POSTGRES_USER: ${KONG_PG_USER:-kong}
+      POSTGRES_PASSWORD: ${KONG_PG_USER:-kong}
+    healthcheck:
+      test: ["CMD", "pg_isready", "-U", "${KONG_PG_USER:-kong}"]
+      interval: 30s
+      timeout: 30s
+      retries: 3
+    restart: on-failure
+    # deploy:
+    #   restart_policy:
+    #     condition: on-failure
+    stdin_open: true
+    tty: true
+
+  # postgres-users:
+  #   image: dojot/postgres:9.4.24-alpine
+  #   restart: on-failure
+  #   command: >
+  #     bash -c "if ! psql -h postgres -U postgres -t -c '\du' | cut -d \| -f 1 | grep -qw kong; then
+  #                  echo 'creating user kong'
+  #                  createuser kong -d -h postgres -U postgres
+  #              else
+  #                  echo 'user kong exists'
+  #              fi
+  #              if ! psql -h postgres -U postgres -lqt | cut -d \| -f 1 | grep -qw kong; then
+  #                  echo 'creating database kong'
+  #                  createdb kong -U kong -h postgres
+  #              else
+  #                  echo 'database kong exists'
+  #              fi"
+  #   depends_on:
+  #     postgres:
+  #       condition: service_healthy
+  #   logging:
+  #     driver: json-file
+  #     options:
+  #       max-size: 100m
+
+  # kong-migration:
+  #   image: kong:2.0.3
+  #   depends_on:
+  #     db:
+  #       condition: service_healthy
+  #   # environment:
+  #   #   - KONG_DATABASE=postgres
+  #   #   - KONG_PG_HOST=postgres
+  #   environment:
+  #     KONG_DATABASE: postgres
+  #     KONG_PG_DATABASE: "kong"
+  #     KONG_PG_HOST: postgres
+  #     KONG_PG_USER: "kong"
+  #     KONG_PG_PASSWORD: "kong"
+  #     KONG_LOG_LEVEL: info
+  #   command: kong migrations bootstrap
+  #   restart: on-failure
+
+  kong-migrations:
+    image:  kong:2.0.3
+    command: kong migrations bootstrap
+    depends_on:
+      - db
+    environment:
+      KONG_DATABASE: postgres
+      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
+      KONG_PG_HOST: db
+      KONG_PG_USER: ${KONG_PG_USER:-kong}
+      KONG_PG_PASSWORD: "kong"
+      KONG_LOG_LEVEL: info
     restart: on-failure
 
   apigw:
-    image: dojot/kong:v0.4.2
-    restart: always
+    image:  kong:test #kong:2.0.3
+    user: "${KONG_USER:-kong}"
     depends_on:
-      postgres:
-        condition: service_healthy
-      kong-migration:
-        condition: service_started
-    ports:
-      - "8000:8000"
+      - db
     environment:
-      KONG_DATABASE: "postgres"
-      KONG_PG_HOST: "postgres"
-    logging:
-      driver: json-file
-      options:
-        max-size: 100m
+      KONG_ADMIN_ACCESS_LOG: /dev/stdout
+      KONG_ADMIN_ERROR_LOG: /dev/stderr
+      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
+      KONG_CASSANDRA_CONTACT_POINTS: db
+      KONG_DATABASE: postgres
+      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
+      KONG_PG_HOST: db
+      KONG_PG_USER: ${KONG_PG_USER:-kong}
+      KONG_PROXY_ACCESS_LOG: /dev/stdout
+      KONG_PROXY_ERROR_LOG: /dev/stderr
+      KONG_PG_PASSWORD: "kong"
+      KONG_LOG_LEVEL: debug
+      # KONG_LUA_PACKAGE_PATH: "/usr/local/custom/?.lua;;"
+      # KONG_PLUGINS:  myplugin
+    ports:
+      - "8000:8000/tcp"
+      - "127.0.0.1:8001:8001/tcp"
+      - "8443:8443/tcp"
+      - "127.0.0.1:8444:8444/tcp"
+    healthcheck:
+      test: ["CMD", "kong", "health"]
+      interval: 10s
+      timeout: 10s
+      retries: 10
+    restart: on-failure
+
+  # apigw:
+  #   image: kong:test
+  #   restart: always
+  #   user: "kong"
+  #   depends_on:
+  #     db:
+  #       condition: service_healthy
+  #     kong-migration:
+  #       condition: service_started
+  #   healthcheck:
+  #     test: ["CMD", "kong", "health"]
+  #     interval: 10s
+  #     timeout: 10s
+  #     retries: 10
+  #   ports:
+  #     - "8000:8000/tcp"
+  #     - "127.0.0.1:8001:8001/tcp"
+  #     - "8443:8443/tcp"
+  #     - "127.0.0.1:8444:8444/tcp"
+  #   environment:
+  #     KONG_ADMIN_ACCESS_LOG: /dev/stdout
+  #     KONG_ADMIN_ERROR_LOG: /dev/stderr
+  #     KONG_ADMIN_LISTEN: '0.0.0.0:8001'
+  #     KONG_CASSANDRA_CONTACT_POINTS: db
+  #     KONG_DATABASE: postgres
+  #     KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
+  #     KONG_PG_HOST: db
+  #     KONG_PG_USER: ${KONG_PG_USER:-kong}
+  #     KONG_PROXY_ACCESS_LOG: /dev/stdout
+  #     KONG_PROXY_ERROR_LOG: /dev/stderr
+  #     KONG_PG_PASSWORD: "kong"
+  #     KONG_LOG_LEVEL: debug
+  #     # KONG_DATABASE: "postgres"
+  #     # KONG_PG_HOST: "postgres"
+  #   logging:
+  #     driver: json-file
+  #     options:
+  #       max-size: 100m
+
+  kong-migrations-up:
+    image:  kong:2.0.3
+    command: kong migrations up && kong migrations finish
+    depends_on:
+      - db
+    environment:
+      KONG_DATABASE: postgres
+      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
+      KONG_PG_HOST: db
+      KONG_PG_USER: ${KONG_PG_USER:-kong}
+      KONG_PG_PASSWORD: "kong"
+      KONG_LOG_LEVEL: info
+    restart: on-failure
 
   kong-config:
     image: dojot/appropriate-curl
@@ -286,6 +394,32 @@ services:
       - apigw
     volumes:
       - ./kong.config.sh:/opt/kong.config.sh:Z
+
+  mongo:
+    image: mongo:4.2.2-bionic
+    ports:
+      - 27017:27017
+    healthcheck:
+      test: echo 'db.stats().ok' | mongo localhost:27017/konga --quiet
+      interval: 30s
+      timeout: 5s
+      retries: 5
+
+  konga:
+    image: pantsel/konga:latest
+    depends_on:
+      - apigw
+    ports:
+      - 1337:1337
+    environment:
+      DB_ADAPTER: mongo
+      DB_DATABASE: konga
+      DB_HOST: mongo
+      KONGA_SEED_USER_DATA_SOURCE_FILE: /kus.js
+      NODE_ENV: production
+    volumes:
+      - ./kus.js:/kus.js:ro
+    restart: on-failure
 
   flowbroker-redis:
     image: dojot/redis:5.0.5-alpine3.10
