.

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -172,6 +172,10 @@ services:
       - DEV_MNGR_CRYPTO_PASS="kamehameHA"
       - DEV_MNGR_CRYPTO_IV=1234567890123456
       - DEV_MNGR_CRYPTO_SALT="shuriken"
+      - DBHOST="postgres"
+      - DBUSER="kong"
+      - DBPASS="kong"
+      - LOG_LEVEL="DEBUG"
     depends_on:
       - postgres
       - kafka
@@ -203,6 +207,7 @@ services:
     environment:
       AUTH_DB_HOST: "postgres"
       AUTH_DB_USER: "kong"
+      AUTH_DB_PWD:  "kong"
       AUTH_KONG_URL: "http://apigw:8001"
       AUTH_CACHE_HOST: "auth-redis"
       # This is used to select the type of cache to be used. Allowed values are "redis" or "nocache"
@@ -214,27 +219,27 @@ services:
       options:
         max-size: 100m
 
-  postgres:
-    image: dojot/postgres:9.4.24-alpine
-    restart: always
-    healthcheck:
-      test: ["CMD", "pg_isready", "-U", "postgres"]
-      interval: 10s
-      timeout: 5s
-      retries: 5
-    logging:
-      driver: json-file
-      options:
-        max-size: 100m
+  # postgres:
+  #   image: dojot/postgres:9.4.24-alpine
+  #   restart: always
+  #   healthcheck:
+  #     test: ["CMD", "pg_isready", "-U", "postgres"]
+  #     interval: 10s
+  #     timeout: 5s
+  #     retries: 5
+  #   logging:
+  #     driver: json-file
+  #     options:
+  #       max-size: 100m
 
-  db:
+  postgres:
     image: postgres:9.5
     environment:
-      POSTGRES_DB: ${KONG_PG_DATABASE:-kong}
-      POSTGRES_USER: ${KONG_PG_USER:-kong}
-      POSTGRES_PASSWORD: ${KONG_PG_USER:-kong}
+      POSTGRES_DB: postgres
+      POSTGRES_USER: postgres
+      POSTGRES_PASSWORD: postgres
     healthcheck:
-      test: ["CMD", "pg_isready", "-U", "${KONG_PG_USER:-kong}"]
+      test: ["CMD", "pg_isready", "-U", "postgres"]
       interval: 30s
       timeout: 30s
       retries: 3
@@ -245,29 +250,29 @@ services:
     stdin_open: true
     tty: true
 
-  # postgres-users:
-  #   image: dojot/postgres:9.4.24-alpine
-  #   restart: on-failure
-  #   command: >
-  #     bash -c "if ! psql -h postgres -U postgres -t -c '\du' | cut -d \| -f 1 | grep -qw kong; then
-  #                  echo 'creating user kong'
-  #                  createuser kong -d -h postgres -U postgres
-  #              else
-  #                  echo 'user kong exists'
-  #              fi
-  #              if ! psql -h postgres -U postgres -lqt | cut -d \| -f 1 | grep -qw kong; then
-  #                  echo 'creating database kong'
-  #                  createdb kong -U kong -h postgres
-  #              else
-  #                  echo 'database kong exists'
-  #              fi"
-  #   depends_on:
-  #     postgres:
-  #       condition: service_healthy
-  #   logging:
-  #     driver: json-file
-  #     options:
-  #       max-size: 100m
+  postgres-users:
+    image: postgres:9.5
+    restart: on-failure
+    command: >
+      bash -c "if ! psql -h postgres -U postgres -t -c '\du' | cut -d \| -f 1 | grep -qw kong; then
+                   echo 'creating user kong'
+                   createuser kong -d -h postgres -U postgres
+               else
+                   echo 'user kong exists'
+               fi
+               if ! psql -h postgres -U postgres -lqt | cut -d \| -f 1 | grep -qw kong; then
+                   echo 'creating database kong'
+                   createdb kong -U kong -h postgres
+               else
+                   echo 'database kong exists'
+               fi"
+    depends_on:
+      postgres:
+        condition: service_healthy
+    logging:
+      driver: json-file
+      options:
+        max-size: 100m
 
   # kong-migration:
   #   image: kong:2.0.3
@@ -291,33 +296,35 @@ services:
     image:  kong:2.0.3
     command: kong migrations bootstrap
     depends_on:
-      - db
+      #- db
+      - postgres
     environment:
       KONG_DATABASE: postgres
       KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
-      KONG_PG_HOST: db
+      KONG_PG_HOST: postgres
       KONG_PG_USER: ${KONG_PG_USER:-kong}
       KONG_PG_PASSWORD: "kong"
-      KONG_LOG_LEVEL: info
+      KONG_LOG_LEVEL: debug
     restart: on-failure
 
   apigw:
     image:  kong:test #kong:2.0.3
-    user: "${KONG_USER:-kong}"
+    user: "kong"
     depends_on:
-      - db
+      #- db
+      - postgres
     environment:
       KONG_ADMIN_ACCESS_LOG: /dev/stdout
       KONG_ADMIN_ERROR_LOG: /dev/stderr
       KONG_ADMIN_LISTEN: '0.0.0.0:8001'
-      KONG_CASSANDRA_CONTACT_POINTS: db
+      KONG_CASSANDRA_CONTACT_POINTS: postgres
       KONG_DATABASE: postgres
-      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
-      KONG_PG_HOST: db
-      KONG_PG_USER: ${KONG_PG_USER:-kong}
+      KONG_PG_DATABASE: kong
+      KONG_PG_HOST: postgres
+      KONG_PG_USER: kong
       KONG_PROXY_ACCESS_LOG: /dev/stdout
       KONG_PROXY_ERROR_LOG: /dev/stderr
-      KONG_PG_PASSWORD: "kong"
+      KONG_PG_PASSWORD: kong
       KONG_LOG_LEVEL: debug
       # KONG_LUA_PACKAGE_PATH: "/usr/local/custom/?.lua;;"
       # KONG_PLUGINS:  myplugin
@@ -376,11 +383,12 @@ services:
     image:  kong:2.0.3
     command: kong migrations up && kong migrations finish
     depends_on:
-      - db
+      #- db
+      - postgres
     environment:
       KONG_DATABASE: postgres
-      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
-      KONG_PG_HOST: db
+      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-postgres}
+      KONG_PG_HOST: postgres
       KONG_PG_USER: ${KONG_PG_USER:-kong}
       KONG_PG_PASSWORD: "kong"
       KONG_LOG_LEVEL: info
